version: '3'

services:
  agl-people-service-consumer:
    image: aglpeopleserviceconsumer:dev
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_agl-people-service-consumer$
    volumes:
      - C:\DEV\AGL-Code-Test\AGL-People-Service-Consumer:/app
      - C:\Users\christian.wilshaw\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_agl-people-service-consumer$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_agl-people-service-consumer$ bin/Debug/netcoreapp2.0/AGL-People-Service-Consumer.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
